SELECT P.PRODUCT_CODE AS PRODUCT_CODE, P.PRICE * C AS SALES
FROM PRODUCT P
JOIN (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS C FROM OFFLINE_SALE GROUP BY PRODUCT_ID) O ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE
