-- 코드를 입력하세요
SELECT DATE_FORMAT(N.SALES_DATE,'%Y-%m-%d') AS SALES_DATE, N.PRODUCT_ID AS PRODUCT_ID, N.USER_ID AS USER_ID, N.SALES_AMOUNT AS SALES_AMOUNT
FROM ONLINE_SALE N
WHERE MONTH(N.SALES_DATE) = 3
UNION ALL
SELECT DATE_FORMAT(F.SALES_DATE,'%Y-%m-%d') AS SALES_DATE, F.PRODUCT_ID AS PRODUCT_ID, NULL AS USER_ID, F.SALES_AMOUNT AS SALES_AMOUNT
FROM OFFLINE_SALE F
WHERE MONTH(F.SALES_DATE) = 3
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID