-- 코드를 입력하세요
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(R.AVG_SCORE,2) AS SCORE 
FROM REST_INFO I
JOIN (SELECT REST_ID, AVG(REVIEW_SCORE) AS AVG_SCORE FROM REST_REVIEW GROUP BY REST_ID) R ON I.REST_ID = R.REST_ID
WHERE I.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, I.FAVORITES DESC