SELECT F1.ID, F2.FISH_NAME, F1.LENGTH
FROM FISH_INFO F1
JOIN FISH_NAME_INFO F2 ON F1.FISH_TYPE = F2.FISH_TYPE
WHERE (F1.FISH_TYPE, F1.LENGTH) IN (
    SELECT FISH_TYPE, MAX(LENGTH)
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
ORDER BY F1.ID;